function createfigure(cdata1, YMatrix1)
%CREATEFIGURE(cdata1, YMatrix1)
%  CDATA1:  image cdata
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 07-Nov-2025 20:55:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.329086021505376 0.775 0.595913978494624]);
hold(axes1,'on');

% Create image
image([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326],...
    [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71],...
    cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create ylabel
ylabel('Trials');

% Create xlabel
xlabel('Time (s)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 326.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 71.5]);
box(axes1,'on');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',16,'Layer','top');
% Create subplot
subplot1 = subplot(4,1,4,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'LineWidth',3);
set(plot1(1),'Color',[0.2422 0.1504 0.6603]);
set(plot1(2),'Color',[0.2813 0.2985 0.9397]);
set(plot1(3),'Color',[0.2006 0.4803 0.9906]);
set(plot1(4),'Color',[0.1288 0.6408 0.891]);
set(plot1(5),'Color',[0.077 0.7468 0.7224]);
set(plot1(6),'Color',[0.3548 0.8016 0.4669]);
set(plot1(7),'Color',[0.7829 0.7579 0.1608]);
set(plot1(8),'Color',[0.9949 0.7915 0.2012]);
set(plot1(9),'Color',[0.9769 0.9839 0.0805]);

% Create xlabel
xlabel('Time (s)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 326]);
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',16);
